/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mde


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MDEStandaloneSetup extends MDEStandaloneSetupGenerated {

	def static void doSetup() {
		new MDEStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
